import sqlite3, os
email = str(input("Email:"))
db = sqlite3.connect(r"{}\db.db".format(os.getcwd()))
cursor = db.cursor()
cursor.execute("""SELECT senha, nome FROM usuarios WHERE email = '{}'""".format(email))
senhadb = cursor.fetchall()
print(senhadb)
print(senhadb[0])
print(senhadb[0][1])
print(senhadb[0][0])